// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkThreats.Data;

#nullable disable

namespace NetworkThreats.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520012347_AddFileAnalysis")]
    partial class AddFileAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NetworkThreats.Models.AttackExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ImpactEstimate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("impact_estimate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ThreatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threat_id");

                    b.Property<string>("UrlReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url_reference");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("attack_examples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImpactEstimate = "130 млн скомпрометированных карт",
                            Name = "Взлом Heartland Payment Systems",
                            ThreatId = 1,
                            UrlReference = "https://en.wikipedia.org/wiki/Heartland_Payment_Systems",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            ImpactEstimate = "Крупнейшая на тот момент DDoS-атака",
                            Name = "DDoS на GitHub (1.35 Тбит/с)",
                            ThreatId = 3,
                            UrlReference = "https://github.blog/2018-03-01-ddos-incident-report/",
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            ImpactEstimate = "Ущерб >4 млрд долларов, 200 000 жертв",
                            Name = "WannaCry ransomware",
                            ThreatId = 5,
                            UrlReference = "https://en.wikipedia.org/wiki/WannaCry_ransomware_attack",
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            ImpactEstimate = "Ущерб >10 млрд долларов",
                            Name = "NotPetya",
                            ThreatId = 5,
                            UrlReference = "https://en.wikipedia.org/wiki/2017_cyberattacks_on_Ukraine",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            ImpactEstimate = "Компрометация сотен TLS-сертификатов",
                            Name = "Атака на DigiNotar",
                            ThreatId = 4,
                            UrlReference = "https://en.wikipedia.org/wiki/DigiNotar",
                            Year = 2011
                        },
                        new
                        {
                            Id = 6,
                            ImpactEstimate = "32 млн паролей в открытом виде",
                            Name = "Взлом RockYou (brute force словарь)",
                            ThreatId = 9,
                            UrlReference = "https://en.wikipedia.org/wiki/RockYou",
                            Year = 2009
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.FileHeuristic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("general")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<string>("PatternType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("string")
                        .HasColumnName("pattern_type");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("medium")
                        .HasColumnName("risk_level");

                    b.HasKey("Id");

                    b.ToTable("file_heuristics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Инъекция процесса",
                            Description = "Выделение исполняемой памяти — характерно для шеллкода и инъекций",
                            Pattern = "VirtualAlloc",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Инъекция процесса",
                            Description = "Запись в память стороннего процесса — классическая техника инъекции",
                            Pattern = "WriteProcessMemory",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Инъекция процесса",
                            Description = "Создание потока в удалённом процессе для выполнения произвольного кода",
                            Pattern = "CreateRemoteThread",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Инъекция процесса",
                            Description = "Низкоуровневый Native API для обхода мониторинга безопасности",
                            Pattern = "NtAllocateVirtualMemory",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Выполнение команд",
                            Description = "Запуск командной строки Windows для выполнения команд",
                            Pattern = "cmd.exe /c",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Выполнение команд",
                            Description = "Обфусцированная команда PowerShell (Base64-encoded payload)",
                            Pattern = "powershell.exe -enc",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Выполнение команд",
                            Description = "PowerShell без профилей — обход политик выполнения скриптов",
                            Pattern = "powershell -nop",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Выполнение команд",
                            Description = "Вызов оболочки Bash — типично для Unix reverse shell",
                            Pattern = "/bin/bash",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Выполнение команд",
                            Description = "Windows API запуска процессов, часто используется вредоносами",
                            Pattern = "ShellExecute",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Загрузка файлов",
                            Description = "PowerShell-команда загрузки файлов с удалённого сервера",
                            Pattern = "Invoke-WebRequest",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Загрузка файлов",
                            Description = "Злоупотребление certutil для декодирования/загрузки Base64-файлов",
                            Pattern = "certutil -decode",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Загрузка файлов",
                            Description = "Злоупотребление BITS для скрытой загрузки файлов",
                            Pattern = "bitsadmin /transfer",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Загрузка файлов",
                            Description = "Метод WebClient для загрузки файлов в .NET",
                            Pattern = "DownloadFile(",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Закрепление",
                            Description = "Запись в ключ автозапуска реестра Windows",
                            Pattern = "CurrentVersion\\Run",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Закрепление",
                            Description = "Создание задания планировщика для персистентного запуска",
                            Pattern = "schtasks /create",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Закрепление",
                            Description = "Помещение файла в папку автозапуска Windows",
                            Pattern = "Startup\\",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Сетевая активность",
                            Description = "Создание сетевого сокета Windows для скрытых коммуникаций",
                            Pattern = "WSASocket",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Сетевая активность",
                            Description = "WinInet API для скрытых HTTP-запросов",
                            Pattern = "InternetOpenUrl",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Сетевая активность",
                            Description = "Bash TCP-редирект — техника reverse shell без netcat",
                            Pattern = "/dev/tcp/",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Ransomware",
                            Description = "Windows CryptoAPI шифрование файлов — индикатор шифровальщика",
                            Pattern = "CryptEncrypt",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Ransomware",
                            Description = "Типичное сообщение-вымогатель о шифровании данных",
                            Pattern = "YOUR FILES ARE ENCRYPTED",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Ransomware",
                            Description = "Упоминание криптовалюты — характерно для требований выкупа",
                            Pattern = "bitcoin",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Анти-анализ",
                            Description = "Проверка наличия отладчика для уклонения от анализа",
                            Pattern = "IsDebuggerPresent",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Анти-анализ",
                            Description = "Обнаружение VirtualBox — уклонение от виртуальных сред",
                            Pattern = "VBOX",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Анти-анализ",
                            Description = "Обнаружение VMware — уклонение от виртуальных сред",
                            Pattern = "VMware",
                            PatternType = "string",
                            RiskLevel = "medium"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Макрос Office",
                            Description = "Автозапускаемый VBA-макрос при открытии документа Office",
                            Pattern = "AutoOpen",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Макрос Office",
                            Description = "Выполнение системных команд из VBA-макроса",
                            Pattern = "Shell(",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 28,
                            Category = "PDF угрозы",
                            Description = "PDF-действие при открытии — может запускать скрипт или URL",
                            Pattern = "/OpenAction",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 29,
                            Category = "PDF угрозы",
                            Description = "JavaScript внутри PDF-файла — типично для эксплойт-документов",
                            Pattern = "/JavaScript",
                            PatternType = "string",
                            RiskLevel = "high"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Упаковщик",
                            Description = "Заголовок UPX-упаковщика — исполняемый файл упакован для обфускации",
                            Pattern = "UPX0",
                            PatternType = "string",
                            RiskLevel = "medium"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.KnownMaliciousHash", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_type");

                    b.Property<string>("Md5")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("md5");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("high")
                        .HasColumnName("severity");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("sha256");

                    b.Property<string>("ThreatName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("threat_name");

                    b.HasKey("Id");

                    b.ToTable("known_malicious_hashes", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Стандартный тестовый файл EICAR для проверки антивирусного ПО.",
                            FileType = "txt",
                            Md5 = "44d88612fea8a8f36de82e1278abb02f",
                            Severity = "medium",
                            Sha256 = "275a021bbfb6489e54d471899f7db9d1663fc695ec2fe2a2c4538aabf651fd0f",
                            ThreatName = "EICAR Test File"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Вирус-вымогатель WannaCry 2017 года, использовавший уязвимость EternalBlue (MS17-010).",
                            FileType = "exe",
                            Md5 = "84c82835a5d21bbcf75a61706d8ab549",
                            Severity = "critical",
                            Sha256 = "ed01ebfbc9eb5bbea545af4d01bf5f1071661840480439c6e5babe8e080e41aa",
                            ThreatName = "WannaCry Ransomware"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Деструктивный вирус NotPetya 2017 года, нацеленный на уничтожение MBR и данных.",
                            FileType = "exe",
                            Md5 = "f1394f06cbf1a84d1e14e54b8dd16d5e",
                            Severity = "critical",
                            Sha256 = "027cc450ef5f8c5f653329641ec1fed91f694e0d229928963b30f6b0d7d3a745",
                            ThreatName = "NotPetya / Petya"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Образец ботнета Mirai, атакующего IoT-устройства через слабые пароли Telnet/SSH.",
                            FileType = "exe",
                            Md5 = "2b28b7f0c7c368b3e82b4f5fa9b51e32",
                            Severity = "critical",
                            Sha256 = "8b553571e82e85cf80c7f58acf8fec1e2a1ca0e2cd6c54d5e28c5ec3c04e9e5",
                            ThreatName = "Mirai Botnet Sample"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Beacon-агент фреймворка Cobalt Strike, используемый для пентеста и APT-атак.",
                            FileType = "dll",
                            Md5 = "a3b4c5d6e7f8901234567890abcdef12",
                            Severity = "high",
                            Sha256 = "4a1f0e6e4e7b1d3f7c2a0b9d5e8f3c1a6b0d2e4f8c7a5b3d9e1f0a2c4b6d8e0",
                            ThreatName = "Cobalt Strike Beacon"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("preventive")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("mitigation_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Параметризованные запросы",
                            ShortDescription = "Использование подготовленных выражений исключает возможность SQL инъекции.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Контентная политика CSP",
                            ShortDescription = "HTTP-заголовок Content-Security-Policy ограничивает источники выполняемых скриптов.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Анти-DDoS фильтрация",
                            ShortDescription = "Специализированные сервисы и оборудование фильтруют аномальный трафик до достижения сервера.",
                            Type = "detective"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TLS/HTTPS шифрование",
                            ShortDescription = "Шифрование трафика исключает перехват и подмену данных при MitM.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Резервное копирование",
                            ShortDescription = "Регулярные изолированные резервные копии позволяют восстановить данные после атаки ransomware.",
                            Type = "corrective"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Обучение сотрудников",
                            ShortDescription = "Информирование пользователей о признаках фишинга снижает вероятность успешной атаки.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CSRF-токены",
                            ShortDescription = "Уникальные токены в формах подтверждают легитимность запроса и блокируют CSRF.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Многофакторная аутентификация",
                            ShortDescription = "MFA делает brute force атаки практически бесполезными даже при компрометации пароля.",
                            Type = "preventive"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ApplicableOs")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("applicable_os");

                    b.Property<string>("CommandExample")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_example");

                    b.Property<int>("MitigationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mitigation_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("MitigationId");

                    b.ToTable("mitigation_steps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Заменить конкатенацию строк в SQL-запросах на параметры (@param)",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Применить ORM (Entity Framework) для исключения ручного SQL",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Action = "Настроить минимальные права учётной записи БД",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Action = "Получить SSL/TLS сертификат (Let's Encrypt или коммерческий)",
                            ApplicableOs = "Все",
                            MitigationId = 4,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            Action = "Настроить редирект HTTP → HTTPS на веб-сервере",
                            ApplicableOs = "Linux/Windows",
                            CommandExample = "app.UseHttpsRedirection();",
                            MitigationId = 4,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Action = "Включить HSTS заголовок для принудительного HTTPS",
                            ApplicableOs = "Все",
                            CommandExample = "app.UseHsts();",
                            MitigationId = 4,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            Action = "Установить и настроить TOTP-приложение (Google Authenticator)",
                            ApplicableOs = "Все",
                            MitigationId = 8,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            Action = "Включить MFA в настройках ASP.NET Core Identity",
                            ApplicableOs = "Все",
                            MitigationId = 8,
                            StepOrder = 2
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AttackVector")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("attack_vector");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int?>("FirstDetectedYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_detected_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("medium")
                        .HasColumnName("severity");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_description");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("threats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackVector = "Веб-формы, параметры URL",
                            CategoryId = 3,
                            FirstDetectedYear = 1998,
                            Name = "SQL Injection",
                            Severity = "high",
                            ShortDescription = "Внедрение вредоносного SQL-кода в запрос к базе данных через пользовательский ввод."
                        },
                        new
                        {
                            Id = 2,
                            AttackVector = "Поля ввода, URL-параметры",
                            CategoryId = 3,
                            FirstDetectedYear = 2005,
                            Name = "Cross-Site Scripting (XSS)",
                            Severity = "medium",
                            ShortDescription = "Внедрение вредоносных скриптов в веб-страницу, выполняемых в браузере жертвы."
                        },
                        new
                        {
                            Id = 3,
                            AttackVector = "Ботнет, UDP/TCP флуд",
                            CategoryId = 2,
                            FirstDetectedYear = 2000,
                            Name = "DDoS-атака",
                            Severity = "high",
                            ShortDescription = "Перегрузка сервера огромным числом ложных запросов с целью отказа в обслуживании."
                        },
                        new
                        {
                            Id = 4,
                            AttackVector = "ARP-спуфинг, подделка DNS",
                            CategoryId = 2,
                            FirstDetectedYear = 1995,
                            Name = "Man-in-the-Middle (MitM)",
                            Severity = "high",
                            ShortDescription = "Перехват и подмена трафика между двумя узлами без их ведома."
                        },
                        new
                        {
                            Id = 5,
                            AttackVector = "Электронная почта, уязвимости SMB",
                            CategoryId = 1,
                            FirstDetectedYear = 2013,
                            Name = "Ransomware",
                            Severity = "critical",
                            ShortDescription = "Вредоносное ПО, шифрующее файлы жертвы с требованием выкупа за ключ расшифровки."
                        },
                        new
                        {
                            Id = 6,
                            AttackVector = "Email, поддельные веб-сайты",
                            CategoryId = 4,
                            FirstDetectedYear = 1996,
                            Name = "Фишинг",
                            Severity = "medium",
                            ShortDescription = "Мошеннические письма и сайты для кражи учётных данных и персональных сведений."
                        },
                        new
                        {
                            Id = 7,
                            AttackVector = "Вредоносная ссылка или страница",
                            CategoryId = 3,
                            FirstDetectedYear = 2001,
                            Name = "CSRF",
                            Severity = "medium",
                            ShortDescription = "Межсайтовая подделка запроса: выполнение нежелательных действий от имени аутентифицированного пользователя."
                        },
                        new
                        {
                            Id = 8,
                            AttackVector = "Общая сеть, Wi-Fi без шифрования",
                            CategoryId = 2,
                            FirstDetectedYear = 1994,
                            Name = "Сниффинг трафика",
                            Severity = "medium",
                            ShortDescription = "Перехват сетевых пакетов для извлечения паролей и конфиденциальных данных."
                        },
                        new
                        {
                            Id = 9,
                            AttackVector = "SSH, RDP, веб-формы авторизации",
                            CategoryId = 2,
                            FirstDetectedYear = 1990,
                            Name = "Brute Force",
                            Severity = "medium",
                            ShortDescription = "Перебор паролей или ключей шифрования методом полного перебора всех возможных значений."
                        },
                        new
                        {
                            Id = 10,
                            AttackVector = "Вложения email, пиратское ПО",
                            CategoryId = 1,
                            FirstDetectedYear = 1998,
                            Name = "Троян удалённого доступа",
                            Severity = "critical",
                            ShortDescription = "Вредоносная программа, предоставляющая злоумышленнику скрытый удалённый доступ к системе жертвы."
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("threat_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Вирусы, черви, трояны, ransomware",
                            Name = "Вредоносное ПО"
                        },
                        new
                        {
                            Id = 2,
                            Description = "DDoS, MitM, сниффинг, спуфинг",
                            Name = "Сетевые атаки"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SQL injection, XSS, CSRF",
                            Name = "Web-атаки"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Фишинг, претекстинг, вишинг",
                            Name = "Социальная инженерия"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Confidence")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("medium")
                        .HasColumnName("confidence");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("IndicatorType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("keyword")
                        .HasColumnName("indicator_type");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("pattern");

                    b.Property<int>("ThreatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threat_id");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("threat_indicators", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Confidence = "high",
                            Description = "Классическая SQL-инъекция через OR-условие",
                            IndicatorType = "keyword",
                            Pattern = "' OR '1'='1",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 2,
                            Confidence = "high",
                            Description = "UNION-based SQL-инъекция для извлечения данных",
                            IndicatorType = "keyword",
                            Pattern = "UNION SELECT",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 3,
                            Confidence = "high",
                            Description = "Деструктивная SQL-команда удаления таблицы",
                            IndicatorType = "keyword",
                            Pattern = "DROP TABLE",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 4,
                            Confidence = "high",
                            Description = "Выполнение ОС-команд через SQL Server",
                            IndicatorType = "keyword",
                            Pattern = "xp_cmdshell",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 5,
                            Confidence = "high",
                            Description = "Цепочка SQL-команд через точку с запятой",
                            IndicatorType = "keyword",
                            Pattern = "'; exec(",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 6,
                            Confidence = "medium",
                            Description = "Обход аутентификации с SQL-комментарием",
                            IndicatorType = "keyword",
                            Pattern = "1=1--",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 7,
                            Confidence = "medium",
                            Description = "Hex-кодированная SQL-инъекция",
                            IndicatorType = "keyword",
                            Pattern = "CAST(0x",
                            ThreatId = 1
                        },
                        new
                        {
                            Id = 8,
                            Confidence = "high",
                            Description = "Внедрение JavaScript через тег <script>",
                            IndicatorType = "keyword",
                            Pattern = "<script>",
                            ThreatId = 2
                        },
                        new
                        {
                            Id = 9,
                            Confidence = "high",
                            Description = "JavaScript URI-схема для XSS",
                            IndicatorType = "keyword",
                            Pattern = "javascript:",
                            ThreatId = 2
                        },
                        new
                        {
                            Id = 10,
                            Confidence = "high",
                            Description = "Event-handler для выполнения скрипта",
                            IndicatorType = "keyword",
                            Pattern = "onerror=",
                            ThreatId = 2
                        },
                        new
                        {
                            Id = 11,
                            Confidence = "high",
                            Description = "Кража cookie-файлов через JavaScript",
                            IndicatorType = "keyword",
                            Pattern = "document.cookie",
                            ThreatId = 2
                        },
                        new
                        {
                            Id = 12,
                            Confidence = "medium",
                            Description = "Динамическое выполнение произвольного кода",
                            IndicatorType = "keyword",
                            Pattern = "eval(",
                            ThreatId = 2
                        },
                        new
                        {
                            Id = 13,
                            Confidence = "high",
                            Description = "Атака переполнения SYN-пакетами",
                            IndicatorType = "keyword",
                            Pattern = "SYN flood",
                            ThreatId = 3
                        },
                        new
                        {
                            Id = 14,
                            Confidence = "medium",
                            Description = "Управление ботнетом для DDoS",
                            IndicatorType = "keyword",
                            Pattern = "botnet",
                            ThreatId = 3
                        },
                        new
                        {
                            Id = 15,
                            Confidence = "medium",
                            Description = "Превышение лимита запросов к серверу",
                            IndicatorType = "log_pattern",
                            Pattern = "too many requests",
                            ThreatId = 3
                        },
                        new
                        {
                            Id = 16,
                            Confidence = "low",
                            Description = "Отказ в обслуживании — сервер перегружен",
                            IndicatorType = "log_pattern",
                            Pattern = "connection refused",
                            ThreatId = 3
                        },
                        new
                        {
                            Id = 17,
                            Confidence = "high",
                            Description = "Подмена ARP-записей для перехвата трафика",
                            IndicatorType = "keyword",
                            Pattern = "ARP spoofing",
                            ThreatId = 4
                        },
                        new
                        {
                            Id = 18,
                            Confidence = "high",
                            Description = "Несоответствие SSL-сертификата — подмена TLS",
                            IndicatorType = "log_pattern",
                            Pattern = "SSL certificate mismatch",
                            ThreatId = 4
                        },
                        new
                        {
                            Id = 19,
                            Confidence = "medium",
                            Description = "Ошибка сертификата — возможная MitM-атака",
                            IndicatorType = "keyword",
                            Pattern = "certificate error",
                            ThreatId = 4
                        },
                        new
                        {
                            Id = 20,
                            Confidence = "high",
                            Description = "Инструмент для MitM-атак Ettercap",
                            IndicatorType = "keyword",
                            Pattern = "ettercap",
                            ThreatId = 4
                        },
                        new
                        {
                            Id = 21,
                            Confidence = "high",
                            Description = "Утилита ARP-спуфинга",
                            IndicatorType = "keyword",
                            Pattern = "arpspoof",
                            ThreatId = 4
                        },
                        new
                        {
                            Id = 22,
                            Confidence = "high",
                            Description = "Семейство ransomware CryptoLocker",
                            IndicatorType = "keyword",
                            Pattern = "CryptoLocker",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 23,
                            Confidence = "high",
                            Description = "Известный шифровальщик WannaCry",
                            IndicatorType = "keyword",
                            Pattern = "WannaCry",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 24,
                            Confidence = "high",
                            Description = "Типичное сообщение ransomware",
                            IndicatorType = "keyword",
                            Pattern = "YOUR_FILES_ARE_ENCRYPTED",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 25,
                            Confidence = "medium",
                            Description = "Расширение зашифрованных файлов",
                            IndicatorType = "keyword",
                            Pattern = ".encrypted",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 26,
                            Confidence = "medium",
                            Description = "Упоминание выкупа",
                            IndicatorType = "keyword",
                            Pattern = "ransom",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 27,
                            Confidence = "medium",
                            Description = "Запуск исполняемых файлов из папки Temp",
                            IndicatorType = "filepath",
                            Pattern = "\\Temp\\",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 28,
                            Confidence = "high",
                            Description = "Деструктивный шифровальщик NotPetya",
                            IndicatorType = "keyword",
                            Pattern = "NotPetya",
                            ThreatId = 5
                        },
                        new
                        {
                            Id = 29,
                            Confidence = "high",
                            Description = "Типичная фраза фишинговых писем",
                            IndicatorType = "keyword",
                            Pattern = "verify your account",
                            ThreatId = 6
                        },
                        new
                        {
                            Id = 30,
                            Confidence = "high",
                            Description = "Психологическое давление в фишинге",
                            IndicatorType = "keyword",
                            Pattern = "your account has been suspended",
                            ThreatId = 6
                        },
                        new
                        {
                            Id = 31,
                            Confidence = "medium",
                            Description = "Создание срочности в фишинговых атаках",
                            IndicatorType = "keyword",
                            Pattern = "urgent action required",
                            ThreatId = 6
                        },
                        new
                        {
                            Id = 32,
                            Confidence = "high",
                            Description = "Тайпсквоттинг домена PayPal",
                            IndicatorType = "domain",
                            Pattern = "paypa1.com",
                            ThreatId = 6
                        },
                        new
                        {
                            Id = 33,
                            Confidence = "medium",
                            Description = "Призыв к действию в фишинговом письме",
                            IndicatorType = "keyword",
                            Pattern = "click here to confirm",
                            ThreatId = 6
                        },
                        new
                        {
                            Id = 34,
                            Confidence = "high",
                            Description = "Отсутствующий CSRF-токен в запросе",
                            IndicatorType = "log_pattern",
                            Pattern = "missing CSRF token",
                            ThreatId = 7
                        },
                        new
                        {
                            Id = 35,
                            Confidence = "high",
                            Description = "Недействительный CSRF-токен",
                            IndicatorType = "log_pattern",
                            Pattern = "invalid csrf",
                            ThreatId = 7
                        },
                        new
                        {
                            Id = 36,
                            Confidence = "low",
                            Description = "Упоминание CSRF в запросе",
                            IndicatorType = "keyword",
                            Pattern = "csrf",
                            ThreatId = 7
                        },
                        new
                        {
                            Id = 37,
                            Confidence = "high",
                            Description = "Сетевой интерфейс в режиме перехвата пакетов",
                            IndicatorType = "keyword",
                            Pattern = "promiscuous mode",
                            ThreatId = 8
                        },
                        new
                        {
                            Id = 38,
                            Confidence = "high",
                            Description = "Интерфейс переведён в promiscuous-режим",
                            IndicatorType = "log_pattern",
                            Pattern = "entered promiscuous",
                            ThreatId = 8
                        },
                        new
                        {
                            Id = 39,
                            Confidence = "medium",
                            Description = "Утилита захвата сетевого трафика",
                            IndicatorType = "keyword",
                            Pattern = "tcpdump",
                            ThreatId = 8
                        },
                        new
                        {
                            Id = 40,
                            Confidence = "medium",
                            Description = "Анализатор сетевых пакетов",
                            IndicatorType = "keyword",
                            Pattern = "wireshark",
                            ThreatId = 8
                        },
                        new
                        {
                            Id = 41,
                            Confidence = "high",
                            Description = "Неудачная попытка SSH-аутентификации",
                            IndicatorType = "log_pattern",
                            Pattern = "Failed password for",
                            ThreatId = 9
                        },
                        new
                        {
                            Id = 42,
                            Confidence = "high",
                            Description = "Попытка входа с несуществующим пользователем",
                            IndicatorType = "log_pattern",
                            Pattern = "Invalid user",
                            ThreatId = 9
                        },
                        new
                        {
                            Id = 43,
                            Confidence = "medium",
                            Description = "Сбой аутентификации",
                            IndicatorType = "log_pattern",
                            Pattern = "authentication failure",
                            ThreatId = 9
                        },
                        new
                        {
                            Id = 44,
                            Confidence = "high",
                            Description = "Инструмент брутфорса Hydra",
                            IndicatorType = "keyword",
                            Pattern = "hydra",
                            ThreatId = 9
                        },
                        new
                        {
                            Id = 45,
                            Confidence = "high",
                            Description = "Инструмент брутфорса Medusa",
                            IndicatorType = "keyword",
                            Pattern = "medusa",
                            ThreatId = 9
                        },
                        new
                        {
                            Id = 46,
                            Confidence = "high",
                            Description = "Metasploit meterpreter — компонент RAT",
                            IndicatorType = "keyword",
                            Pattern = "meterpreter",
                            ThreatId = 10
                        },
                        new
                        {
                            Id = 47,
                            Confidence = "high",
                            Description = "Reverse shell через netcat",
                            IndicatorType = "keyword",
                            Pattern = "nc -e",
                            ThreatId = 10
                        },
                        new
                        {
                            Id = 48,
                            Confidence = "high",
                            Description = "Техника обратного подключения к атакующему",
                            IndicatorType = "keyword",
                            Pattern = "reverse shell",
                            ThreatId = 10
                        },
                        new
                        {
                            Id = 49,
                            Confidence = "high",
                            Description = "Маскировка RAT под системный процесс svchost",
                            IndicatorType = "filepath",
                            Pattern = "\\Temp\\svchost",
                            ThreatId = 10
                        },
                        new
                        {
                            Id = 50,
                            Confidence = "high",
                            Description = "Перехватчик нажатий клавиш",
                            IndicatorType = "keyword",
                            Pattern = "keylogger",
                            ThreatId = 10
                        },
                        new
                        {
                            Id = 51,
                            Confidence = "high",
                            Description = "Обфусцированная команда PowerShell (base64)",
                            IndicatorType = "keyword",
                            Pattern = "powershell -enc",
                            ThreatId = 10
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatMitigation", b =>
                {
                    b.Property<int>("ThreatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threat_id");

                    b.Property<int>("MitigationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mitigation_id");

                    b.Property<string>("Effectiveness")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("effectiveness");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("ThreatId", "MitigationId");

                    b.HasIndex("MitigationId");

                    b.ToTable("threat_mitigation", (string)null);

                    b.HasData(
                        new
                        {
                            ThreatId = 1,
                            MitigationId = 1,
                            Effectiveness = "high",
                            Notes = "Полностью устраняет вектор атаки"
                        },
                        new
                        {
                            ThreatId = 2,
                            MitigationId = 2,
                            Effectiveness = "high",
                            Notes = "CSP блокирует выполнение внешних скриптов"
                        },
                        new
                        {
                            ThreatId = 3,
                            MitigationId = 3,
                            Effectiveness = "medium",
                            Notes = "Снижает нагрузку, но не устраняет атаку полностью"
                        },
                        new
                        {
                            ThreatId = 4,
                            MitigationId = 4,
                            Effectiveness = "high",
                            Notes = "TLS делает перехват трафика бесполезным"
                        },
                        new
                        {
                            ThreatId = 5,
                            MitigationId = 5,
                            Effectiveness = "high",
                            Notes = "Изолированные копии не затрагиваются шифровальщиком"
                        },
                        new
                        {
                            ThreatId = 6,
                            MitigationId = 6,
                            Effectiveness = "medium",
                            Notes = "Снижает вероятность, но не исключает успешный фишинг"
                        },
                        new
                        {
                            ThreatId = 7,
                            MitigationId = 7,
                            Effectiveness = "high",
                            Notes = "CSRF-токен проверяет источник запроса"
                        },
                        new
                        {
                            ThreatId = 9,
                            MitigationId = 8,
                            Effectiveness = "high",
                            Notes = "Второй фактор блокирует атаку даже при подобранном пароле"
                        },
                        new
                        {
                            ThreatId = 8,
                            MitigationId = 4,
                            Effectiveness = "high",
                            Notes = "Шифрование делает перехваченный трафик нечитаемым"
                        },
                        new
                        {
                            ThreatId = 10,
                            MitigationId = 6,
                            Effectiveness = "medium",
                            Notes = "Обучение снижает риск запуска трояна через социальную инженерию"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.AttackExample", b =>
                {
                    b.HasOne("NetworkThreats.Models.Threat", "Threat")
                        .WithMany("AttackExamples")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationStep", b =>
                {
                    b.HasOne("NetworkThreats.Models.MitigationMethod", "MitigationMethod")
                        .WithMany("MitigationSteps")
                        .HasForeignKey("MitigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MitigationMethod");
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.HasOne("NetworkThreats.Models.ThreatCategory", "Category")
                        .WithMany("Threats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatIndicator", b =>
                {
                    b.HasOne("NetworkThreats.Models.Threat", "Threat")
                        .WithMany()
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatMitigation", b =>
                {
                    b.HasOne("NetworkThreats.Models.MitigationMethod", "MitigationMethod")
                        .WithMany("ThreatMitigations")
                        .HasForeignKey("MitigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetworkThreats.Models.Threat", "Threat")
                        .WithMany("ThreatMitigations")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MitigationMethod");

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationMethod", b =>
                {
                    b.Navigation("MitigationSteps");

                    b.Navigation("ThreatMitigations");
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.Navigation("AttackExamples");

                    b.Navigation("ThreatMitigations");
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatCategory", b =>
                {
                    b.Navigation("Threats");
                });
#pragma warning restore 612, 618
        }
    }
}
