// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetworkThreats.Data;

#nullable disable

namespace NetworkThreats.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260519195323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("NetworkThreats.Models.AttackExample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ImpactEstimate")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("impact_estimate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("ThreatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threat_id");

                    b.Property<string>("UrlReference")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("url_reference");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ThreatId");

                    b.ToTable("attack_examples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImpactEstimate = "130 млн скомпрометированных карт",
                            Name = "Взлом Heartland Payment Systems",
                            ThreatId = 1,
                            UrlReference = "https://en.wikipedia.org/wiki/Heartland_Payment_Systems",
                            Year = 2008
                        },
                        new
                        {
                            Id = 2,
                            ImpactEstimate = "Крупнейшая на тот момент DDoS-атака",
                            Name = "DDoS на GitHub (1.35 Тбит/с)",
                            ThreatId = 3,
                            UrlReference = "https://github.blog/2018-03-01-ddos-incident-report/",
                            Year = 2018
                        },
                        new
                        {
                            Id = 3,
                            ImpactEstimate = "Ущерб >4 млрд долларов, 200 000 жертв",
                            Name = "WannaCry ransomware",
                            ThreatId = 5,
                            UrlReference = "https://en.wikipedia.org/wiki/WannaCry_ransomware_attack",
                            Year = 2017
                        },
                        new
                        {
                            Id = 4,
                            ImpactEstimate = "Ущерб >10 млрд долларов",
                            Name = "NotPetya",
                            ThreatId = 5,
                            UrlReference = "https://en.wikipedia.org/wiki/2017_cyberattacks_on_Ukraine",
                            Year = 2017
                        },
                        new
                        {
                            Id = 5,
                            ImpactEstimate = "Компрометация сотен TLS-сертификатов",
                            Name = "Атака на DigiNotar",
                            ThreatId = 4,
                            UrlReference = "https://en.wikipedia.org/wiki/DigiNotar",
                            Year = 2011
                        },
                        new
                        {
                            Id = 6,
                            ImpactEstimate = "32 млн паролей в открытом виде",
                            Name = "Взлом RockYou (brute force словарь)",
                            ThreatId = 9,
                            UrlReference = "https://en.wikipedia.org/wiki/RockYou",
                            Year = 2009
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_description");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("preventive")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("mitigation_methods", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Параметризованные запросы",
                            ShortDescription = "Использование подготовленных выражений исключает возможность SQL инъекции.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Контентная политика CSP",
                            ShortDescription = "HTTP-заголовок Content-Security-Policy ограничивает источники выполняемых скриптов.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Анти-DDoS фильтрация",
                            ShortDescription = "Специализированные сервисы и оборудование фильтруют аномальный трафик до достижения сервера.",
                            Type = "detective"
                        },
                        new
                        {
                            Id = 4,
                            Name = "TLS/HTTPS шифрование",
                            ShortDescription = "Шифрование трафика исключает перехват и подмену данных при MitM.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Резервное копирование",
                            ShortDescription = "Регулярные изолированные резервные копии позволяют восстановить данные после атаки ransomware.",
                            Type = "corrective"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Обучение сотрудников",
                            ShortDescription = "Информирование пользователей о признаках фишинга снижает вероятность успешной атаки.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 7,
                            Name = "CSRF-токены",
                            ShortDescription = "Уникальные токены в формах подтверждают легитимность запроса и блокируют CSRF.",
                            Type = "preventive"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Многофакторная аутентификация",
                            ShortDescription = "MFA делает brute force атаки практически бесполезными даже при компрометации пароля.",
                            Type = "preventive"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("ApplicableOs")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("applicable_os");

                    b.Property<string>("CommandExample")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("command_example");

                    b.Property<int>("MitigationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mitigation_id");

                    b.Property<int>("StepOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("step_order");

                    b.HasKey("Id");

                    b.HasIndex("MitigationId");

                    b.ToTable("mitigation_steps", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Action = "Заменить конкатенацию строк в SQL-запросах на параметры (@param)",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Action = "Применить ORM (Entity Framework) для исключения ручного SQL",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Action = "Настроить минимальные права учётной записи БД",
                            ApplicableOs = "Все",
                            MitigationId = 1,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Action = "Получить SSL/TLS сертификат (Let's Encrypt или коммерческий)",
                            ApplicableOs = "Все",
                            MitigationId = 4,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 5,
                            Action = "Настроить редирект HTTP → HTTPS на веб-сервере",
                            ApplicableOs = "Linux/Windows",
                            CommandExample = "app.UseHttpsRedirection();",
                            MitigationId = 4,
                            StepOrder = 2
                        },
                        new
                        {
                            Id = 6,
                            Action = "Включить HSTS заголовок для принудительного HTTPS",
                            ApplicableOs = "Все",
                            CommandExample = "app.UseHsts();",
                            MitigationId = 4,
                            StepOrder = 3
                        },
                        new
                        {
                            Id = 7,
                            Action = "Установить и настроить TOTP-приложение (Google Authenticator)",
                            ApplicableOs = "Все",
                            MitigationId = 8,
                            StepOrder = 1
                        },
                        new
                        {
                            Id = 8,
                            Action = "Включить MFA в настройках ASP.NET Core Identity",
                            ApplicableOs = "Все",
                            MitigationId = 8,
                            StepOrder = 2
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("AttackVector")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("attack_vector");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("category_id");

                    b.Property<int?>("FirstDetectedYear")
                        .HasColumnType("INTEGER")
                        .HasColumnName("first_detected_year");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("medium")
                        .HasColumnName("severity");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("short_description");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("threats", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AttackVector = "Веб-формы, параметры URL",
                            CategoryId = 3,
                            FirstDetectedYear = 1998,
                            Name = "SQL Injection",
                            Severity = "high",
                            ShortDescription = "Внедрение вредоносного SQL-кода в запрос к базе данных через пользовательский ввод."
                        },
                        new
                        {
                            Id = 2,
                            AttackVector = "Поля ввода, URL-параметры",
                            CategoryId = 3,
                            FirstDetectedYear = 2005,
                            Name = "Cross-Site Scripting (XSS)",
                            Severity = "medium",
                            ShortDescription = "Внедрение вредоносных скриптов в веб-страницу, выполняемых в браузере жертвы."
                        },
                        new
                        {
                            Id = 3,
                            AttackVector = "Ботнет, UDP/TCP флуд",
                            CategoryId = 2,
                            FirstDetectedYear = 2000,
                            Name = "DDoS-атака",
                            Severity = "high",
                            ShortDescription = "Перегрузка сервера огромным числом ложных запросов с целью отказа в обслуживании."
                        },
                        new
                        {
                            Id = 4,
                            AttackVector = "ARP-спуфинг, подделка DNS",
                            CategoryId = 2,
                            FirstDetectedYear = 1995,
                            Name = "Man-in-the-Middle (MitM)",
                            Severity = "high",
                            ShortDescription = "Перехват и подмена трафика между двумя узлами без их ведома."
                        },
                        new
                        {
                            Id = 5,
                            AttackVector = "Электронная почта, уязвимости SMB",
                            CategoryId = 1,
                            FirstDetectedYear = 2013,
                            Name = "Ransomware",
                            Severity = "critical",
                            ShortDescription = "Вредоносное ПО, шифрующее файлы жертвы с требованием выкупа за ключ расшифровки."
                        },
                        new
                        {
                            Id = 6,
                            AttackVector = "Email, поддельные веб-сайты",
                            CategoryId = 4,
                            FirstDetectedYear = 1996,
                            Name = "Фишинг",
                            Severity = "medium",
                            ShortDescription = "Мошеннические письма и сайты для кражи учётных данных и персональных сведений."
                        },
                        new
                        {
                            Id = 7,
                            AttackVector = "Вредоносная ссылка или страница",
                            CategoryId = 3,
                            FirstDetectedYear = 2001,
                            Name = "CSRF",
                            Severity = "medium",
                            ShortDescription = "Межсайтовая подделка запроса: выполнение нежелательных действий от имени аутентифицированного пользователя."
                        },
                        new
                        {
                            Id = 8,
                            AttackVector = "Общая сеть, Wi-Fi без шифрования",
                            CategoryId = 2,
                            FirstDetectedYear = 1994,
                            Name = "Сниффинг трафика",
                            Severity = "medium",
                            ShortDescription = "Перехват сетевых пакетов для извлечения паролей и конфиденциальных данных."
                        },
                        new
                        {
                            Id = 9,
                            AttackVector = "SSH, RDP, веб-формы авторизации",
                            CategoryId = 2,
                            FirstDetectedYear = 1990,
                            Name = "Brute Force",
                            Severity = "medium",
                            ShortDescription = "Перебор паролей или ключей шифрования методом полного перебора всех возможных значений."
                        },
                        new
                        {
                            Id = 10,
                            AttackVector = "Вложения email, пиратское ПО",
                            CategoryId = 1,
                            FirstDetectedYear = 1998,
                            Name = "Троян удалённого доступа",
                            Severity = "critical",
                            ShortDescription = "Вредоносная программа, предоставляющая злоумышленнику скрытый удалённый доступ к системе жертвы."
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("threat_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Вирусы, черви, трояны, ransomware",
                            Name = "Вредоносное ПО"
                        },
                        new
                        {
                            Id = 2,
                            Description = "DDoS, MitM, сниффинг, спуфинг",
                            Name = "Сетевые атаки"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SQL injection, XSS, CSRF",
                            Name = "Web-атаки"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Фишинг, претекстинг, вишинг",
                            Name = "Социальная инженерия"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatMitigation", b =>
                {
                    b.Property<int>("ThreatId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("threat_id");

                    b.Property<int>("MitigationId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("mitigation_id");

                    b.Property<string>("Effectiveness")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("effectiveness");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.HasKey("ThreatId", "MitigationId");

                    b.HasIndex("MitigationId");

                    b.ToTable("threat_mitigation", (string)null);

                    b.HasData(
                        new
                        {
                            ThreatId = 1,
                            MitigationId = 1,
                            Effectiveness = "high",
                            Notes = "Полностью устраняет вектор атаки"
                        },
                        new
                        {
                            ThreatId = 2,
                            MitigationId = 2,
                            Effectiveness = "high",
                            Notes = "CSP блокирует выполнение внешних скриптов"
                        },
                        new
                        {
                            ThreatId = 3,
                            MitigationId = 3,
                            Effectiveness = "medium",
                            Notes = "Снижает нагрузку, но не устраняет атаку полностью"
                        },
                        new
                        {
                            ThreatId = 4,
                            MitigationId = 4,
                            Effectiveness = "high",
                            Notes = "TLS делает перехват трафика бесполезным"
                        },
                        new
                        {
                            ThreatId = 5,
                            MitigationId = 5,
                            Effectiveness = "high",
                            Notes = "Изолированные копии не затрагиваются шифровальщиком"
                        },
                        new
                        {
                            ThreatId = 6,
                            MitigationId = 6,
                            Effectiveness = "medium",
                            Notes = "Снижает вероятность, но не исключает успешный фишинг"
                        },
                        new
                        {
                            ThreatId = 7,
                            MitigationId = 7,
                            Effectiveness = "high",
                            Notes = "CSRF-токен проверяет источник запроса"
                        },
                        new
                        {
                            ThreatId = 9,
                            MitigationId = 8,
                            Effectiveness = "high",
                            Notes = "Второй фактор блокирует атаку даже при подобранном пароле"
                        },
                        new
                        {
                            ThreatId = 8,
                            MitigationId = 4,
                            Effectiveness = "high",
                            Notes = "Шифрование делает перехваченный трафик нечитаемым"
                        },
                        new
                        {
                            ThreatId = 10,
                            MitigationId = 6,
                            Effectiveness = "medium",
                            Notes = "Обучение снижает риск запуска трояна через социальную инженерию"
                        });
                });

            modelBuilder.Entity("NetworkThreats.Models.AttackExample", b =>
                {
                    b.HasOne("NetworkThreats.Models.Threat", "Threat")
                        .WithMany("AttackExamples")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationStep", b =>
                {
                    b.HasOne("NetworkThreats.Models.MitigationMethod", "MitigationMethod")
                        .WithMany("MitigationSteps")
                        .HasForeignKey("MitigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MitigationMethod");
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.HasOne("NetworkThreats.Models.ThreatCategory", "Category")
                        .WithMany("Threats")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatMitigation", b =>
                {
                    b.HasOne("NetworkThreats.Models.MitigationMethod", "MitigationMethod")
                        .WithMany("ThreatMitigations")
                        .HasForeignKey("MitigationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NetworkThreats.Models.Threat", "Threat")
                        .WithMany("ThreatMitigations")
                        .HasForeignKey("ThreatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MitigationMethod");

                    b.Navigation("Threat");
                });

            modelBuilder.Entity("NetworkThreats.Models.MitigationMethod", b =>
                {
                    b.Navigation("MitigationSteps");

                    b.Navigation("ThreatMitigations");
                });

            modelBuilder.Entity("NetworkThreats.Models.Threat", b =>
                {
                    b.Navigation("AttackExamples");

                    b.Navigation("ThreatMitigations");
                });

            modelBuilder.Entity("NetworkThreats.Models.ThreatCategory", b =>
                {
                    b.Navigation("Threats");
                });
#pragma warning restore 612, 618
        }
    }
}
